package consts

// 此文件不可被直接篡改，请运行翻译小工具，请参考 (translation/translation.go)
// 任何于此文件的直接篡改，可能会被小工具覆盖而使到系统崩溃。
var (
	WrongConfirmationPassword = "wrong_confirmation_password"
	SetGroupOwnerFailed = "set_group_owner_failed"
	RemoveContactFailed = "remove_contact_failed"
	RemoveContactSuccess = "remove_contact_success"
	CreateContactFailed = "create_contact_failed"
	AddGroupMemberFailed = "add_group_member_failed"
	ContactNotFound = "contact_not_found"
	AcceptContactFailed = "accept_contact_failed"
	AcceptContactSuccess = "accept_contact_success"
	Success = "success"
	MemberNotInGroup = "member_not_in_group"
	DisbandGroupFailed = "disband_group_failed"
	CannotCreateGroupingOwnAcc = "cannot_create_grouping_own_acc"
	WaitingPreviousActionToBeCompleted = "waiting_previous_action_to_be_completed"
	Failed = "failed"
	CreateContactSearchContactCrashed = "create_contact_search_contact_crashed"
	SetGroupAdminFailed = "set_group_admin_failed"
	CreateGroupingFailed = "create_grouping_failed"
	UserNotFound = "user_not_found"
	RemoveGroupMemberFailed = "remove_group_member_failed"
	UserFound = "user_found"
	InvalidUsernamePassword = "invalid_username_password"
	CreateGroupFailed = "create_group_failed"
	GetGroupInfoFailed = "get_group_info_failed"
	NoGroupAuthority = "no_group_authority"
	MemberAlreadyInGroup = "member_already_in_group"
	CreateContactSuccess = "create_contact_success"
	CreateContactCannotAddOwnAcc = "create_contact_cannot_add_own_acc"
	CreateGroupingSuccess = "create_grouping_success"
	CreateContactRequestDuplicated = "create_contact_request_duplicated"
	GroupDoesNotExist = "group_does_not_exist"
	ContactCannotRemoveOwnAcc = "contact_cannot_remove_own_acc"
	)
