package consts

// 这里定义的常量，一般是具有错误代码+错误说明组成，一般用于接口返回
var (
	Success                           = "success"
	Failed                            = "failed"
	UserFound                         = "user_found"
	UserNotFound                      = "user_not_found"
	InvalidUsernamePassword           = "invalid_username_password"
	WrongConfirmationPassword         = "wrong_confirmation_password"
	CreateContactSuccess              = "create_contact_success"
	CreateContactFailed               = "create_contact_failed"
	CreateContactCannotAddOwnAcc      = "create_contact_cannot_add_own_acc"
	CreateContactSearchContactCrashed = "create_contact_search_contact_crashed"
	CreateContactRequestDuplicated    = "create_contact_request_duplicated"
	CreateGroupFailed                 = "create_group_failed"
	AddGroupMemberFailed              = "add_group_member_failed"
	SetGroupAdminFailed               = "set_group_admin_failed"
	SetGroupOwnerFailed               = "set_group_owner_failed"
	GetGroupInfoFailed                = "get_group_info_failed"
	NoGroupAuthority                  = "no_group_authority"
	MemberExistInGroup                = "member_already_in_group"
	MemberNotInGroup                  = "member_not_in_group"
	RemoveGroupMemberFailed           = "remove_group_member_failed"
	GroupDoesNotExist                 = "group_does_not_exist"
	DisbandGroupFailed                = "disband_group_failed"
	ContactNotFound                   = "contact_not_found"
	AcceptContactFailed               = "accept_contact_failed"
	AcceptContactSuccess              = "accept_contact_success"
	RemoveContactFailed               = "remove_contact_failed"
	RemoveContactSuccess              = "remove_contact_success"
	ContactCannotRemoveOwnAcc         = "contact_cannot_remove_own_acc"
	CannotCreateGroupingOwnAcc        = "cannot_create_grouping_own_acc"
	CreateGroupingFailed              = "create_grouping_failed"
	CreateGroupingSuccess             = "create_grouping_success"
)
